### ISSUE TITLE
DMT 0.9.26-4.1.hotfix2 ModuleNotFoundError

### ISSUE THREAD

**Issue by taw00** [taw00/dashcore-rpm#1]
[todd@localhost dashcore-rpm]$ /usr/share/dash-masternode-tool/dash-masternode-tool-desktop-script.sh
Kicking off 'dash-masternode-tool --data-dir <data-directory> --config <configuration file>'
... first sniffing at '~/.config/dmt/' then '~/.dmt/'
... found ~/.config/dmt/ ... setting to m750 for better protection.
/usr/share/dash-masternode-tool/dash-masternode-tool-desktop-script.sh: line 58: [: missing `]'
... found a config file /home/todd/.config/dmt/config-v4.ini
Running /usr/share/dash-masternode-tool/DashMasternodeTool --data-dir /home/todd/.config/dmt --config /home/todd/.config/dmt/config-v4.ini
Traceback (most recent call last):
  File "PyInstaller/loader/rthooks/pyi_rth_pkgres.py", line 13, in <module>
  File "/builddir/build/BUILD/dash-masternode-tool-0.9/venv/lib/python3.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 623, in exec_module
  File "pkg_resources/__init__.py", line 86, in <module>
ModuleNotFoundError: No module named 'pkg_resources.py2_warn'
[5432] Failed to execute script pyi_rth_pkgres

**Comment by taw00** [comment]
This is some issue associated with setuptools 45.0.0. Or some such. Reference <https://github.com/pypa/setuptools/issues/1963>

**Comment by taw00** [comment]
Resolved. by forcing setuptools 44.0.0 (in the specfile) instead of 45.0.0

**Comment by nicker-bocker** [comment]
> Resolved. by forcing setuptools 44.0.0 instead of 45.0.0

This worked for me as well
