### ISSUE TITLE
EOL clarification

### ISSUE THREAD

**Issue by thephez** [taw00/dashcore-rpm#7]
I saw the EOL message in the readme and just wanted to check if v17 is the last version you're supporting? I thought that's what you meant, but then noticed some commits with a v18 URL.

We will remove the info from https://docs.dash.org/en/stable/masternodes/advanced.html#installing-dash-on-fedora-linux if v18 isn't supported, but will leave it there otherwise.

**Comment by taw00** [comment]
moot issue.
